# Generated by Django 4.2.27 on 2025-12-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('moral_theme', models.CharField(max_length=100)),
                ('prompt', models.TextField(blank=True)),
                ('avatar_path', models.CharField(blank=True, max_length=500, null=True)),
                ('llm_provider', models.CharField(default='openai', max_length=50)),
                ('image_provider', models.CharField(default='stub', max_length=50)),
                ('tts_provider', models.CharField(default='stub', max_length=50)),
                ('story_json', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_calls_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Story Request',
                'verbose_name_plural': 'Story Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.IntegerField()),
                ('text', models.TextField()),
                ('image_prompt', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('decision', models.JSONField(blank=True, default=dict, null=True)),
                ('applied_decision', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.storyrequest')),
            ],
            options={
                'ordering': ['story_request', 'scene_id'],
                'unique_together': {('story_request', 'scene_id')},
            },
        ),
        migrations.CreateModel(
            name='UserDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decisions', to='core.storyscene')),
                ('story_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.storyrequest')),
            ],
            options={
                'ordering': ['story_request', 'created_at'],
            },
        ),
    ]
