# Generated by Django 4.2.29 on 2026-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storyrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrequest',
            name='child_age',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='storyrequest',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=2),
        ),
    ]
