# Generated by Django 4.2.29 on 2026-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
