# Generated by Django 4.2.29 on 2026-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_emailverification_token_emailverification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrequest',
            name='ghibli_avatar_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
